# name属性用来指定这个工作流的名字
name: Visit_websites_regularly

# 这个部分用来指定能够触发工作流执行的事件
on:
  schedule:
    - cron: "0 2 * * *"



# 工作流是由一个或多个的jobs构成的，在jobs里来说明要交给GitHub aciton执行的任务
jobs:
  # 这个jobs中的一个任务，名字叫build(随便怎么取)
  build:
    # 用来指定这个任务在什么操作系统上跑(服务器是GitHub免费提供的)
    runs-on: ubuntu-latest

    # 指出这个build任务的步骤
    steps:

      # 步骤，这里只写了一个步骤，目的是输出hello github acition
      - name: visit web
        run: |
          echo Hello, github action!
          ping flyfish.cloudns.ch
          ping saber1360.cloudns.ch
          ping wonder.cloudns.ch

